name: api test

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: pulling code
        uses: actions/checkout@v1

      - name: setting up python
        uses: actions/setup-python@v1
        with:
          python-version: 3.9

      - name: installing dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: start api
        run: python server.py

      - name: test api
        run: curl http://127.0.0.1:5000/health | grep "working"